name: Deploy lib

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install nestjs cli
      run: npm i -g @nestjs/cli
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: npm run test:cov
    - name: Run build
      run: npm run build
    - name: copy package.json
      run: cp package.json dist/package.json
    - name: publish to npm
      run: cd dist && npm publish